-include device/semc/msm7x27-common/BoardConfigCommon.mk

TARGET_BOOTLOADER_BOARD_NAME := delta
TARGET_OTA_ASSERT_DEVICE := U20i,U20a,mimmi
PRODUCT_BUILD_PROP_OVERRIDES += TARGET_BOOTLOADER_BOARD_NAME=mimmi

BOARD_HAS_SMALL_RECOVERY := true
BOARD_HAS_JANKY_BACKBUFFER := true
BOARD_LDPI_RECOVERY := true

## TWRP
DEVICE_RESOLUTION := 240x320
